### ISSUE TITLE
Rotate Screen 90 (or 270)?

### ISSUE THREAD

**Issue by oddboy** [kevinkahn/softconsole#10] opened 2020-10-07 05:10 UTC
Hi, 
wicked cool project!  thank you so much for your on-going efforts to maintain this.  It's *exactly* what I need!

I've fot an RPI 4B hooked up to an RPI Official 7" Touchscreen.  I havve the screen rotated 270' from normal so that it displays in Portrait mode rather than Landscape.  It took me a couple of days to figure out how to do this as the 4B doesn't use the same old "lcd_rotate" config directives that older model used.  I had to rotate the screen using the screen config utility on the main Pi menu, then I had to edit one of the  xorg config files to rotate the touch screen.

Anyway, I'd love to find a way to rotate softconsole as well, but I can't figure out where/how to do this.

Any suggestions or hints?  All other apps just use the screen orientation the system is set for, but softconsole seems to only run in landscape mode for me.

thanks!

Joel

**Comment by kevinkahn** [comment] 2020-10-07 18:40
Interestingly the system doesn't seem to rotate the screen event coordinates for the 7" touchscreen whereas it does for the smaller screens.  I don't have a PI4 so can't guarantee that my fix will work for you.  However, I did rotate the screen on a Pi3 with the display_lcd_rotate and could reproduce a problem.  The touch points reports are still as though the screen was in landscape.  This does not happen with a simple vertical flip using lcd_rotate - that correctly adjusts the reported points.  I can't tell from your comment whether the screen display is rotated for you and it is just the touch that isn't working.  For the moment I'll assume that is the case but let me know if the screen painting is wrong.  Since I just ask the underlying Pythion graphics system for the screen size/shape I would expect that should be ok.  The touch stuff is handled directly by console code for reasons having to do with "permanent" bugs in the Python touch handling system.

 So I added a facility to tell softconsole to swap the axes (and in the case of the 7in screen you also flip one of the axes so that 0 on that dimension is at the top left).  I've got that version now sitting as the currentbeta release in case you want to try it.  There are 1 or 2 things you will need to change at a configuration level for that code.
1) in your config directory (usually ~pi/Console) create a file called touchmodifier with the content "portraitright" or "portraitleft"  (no quotes).  The right/left refers to the side of the console from which the power cord comes out.  Which axis needs flipping depends on this.
2) you should see in the downloaded beta version that there are 2 additional lines in the touchdefinitions file that has the name "raspberrypi-ts.portraitright" and "raspberrypi-ts.portraitleft".  These add a trailing parameter which tells the console to swap what it thinks are the x and y axes and it also sets one of the "flips" to the length of that axis (800 or 480).  A non-zero flip causes it to subtract that coordinate of a touchpoint from the given value (which is the resolution in that direction) so as to invert the direction of the axis.  You should not need to touch this but if you are still getting incorrect touch positions it may be useful to know.

I think if you just add the touchmodifier file per (1) you should get what you want.  However, since I don't have a pi4 I can't be sure.  I'm going to run this version for a bit here just to make sure I didn't break something along the way and then push it as a current release.  However, if you try the beta and have more issues I'll try to sort those out first.  Let me know.

**Comment by oddboy** [comment] 2020-10-08 01:11
thank you Kevin!  I will give it a try tonight!

regarding the rotation with the Pi4B, I had to do two things.

1.) rotate the screen using the screen config applet on the main Pi menu (in the GUI)
2.) edit the /usr/share/X11/xorg.conf.d/40-libinput.conf file

This is what the section in the libinput file labeled as "touchscreen catchall" looks like with my edit added:

Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"     # < this is the line i added.  this swaps the touchscreen portion of the 7" display
EndSection

I'll go back through my browser history and get the link to the page I found for this part.

FWIW, the old way (lcd_rotate) sounds MUCH easier.  Apparently, you can disable the FMKS drivers on the 4B and make it behave like the Pi3 and lower screens, but then you lose out on 3d acceleration... I guess maybe that would be OK give that I won't be watching videos or playing games on these...

This is from the /boot/config.txt on the Pi4B:

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d

Anyway, thank you so much for the quick response and with a (potential) fix no less!  I'll let you know how it works for me.

best,

Joel


________________________________

**Comment by oddboy** [comment] 2020-10-08 02:21
hey Kevin,

FWIW, I had a couple other difficulties in getting things set up.  I'd submit a PR, but I haven't actually fixed the code, just worked around the issues.

there were two things:

* couldn't get weatherbit to work.  log shows: &key=&lat... (i.e. the api key was not being passed into the Api class)

to get it to work, I hard coded my key into </home/pi/consolestable/stores/weathprov/_weatherbit/api.py>

* weatherbit was showing degF despite adding the 'units='M' to the weather provider file.  to show degC, I changed the format string in </home/pi/consolestable/screens/weatherscreen.py>
self.condformat = u"{d[0]} {d[1]}\u00B0C", u"  Feels like: {d[2]}\u00B0C", "Wind {d[3]}@{d[4]}"
(the "C" was "F" in this string)

cheers,

Joel
________________________________

**Comment by kevinkahn** [comment] 2020-10-08 03:03
Joel,
Thanks for helping debug - always useful.

To the first item - I can't reproduce.  No matter what I try I generate an URL with the key filled in.  Clearly what is happening is that the key is not being parsed out of the config files.  For comparison I have an entry with my password stuff that reads:
[Weatherbit]
    type = WeatherProvider
    apikey = '0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx3'
which give the console the apikey.  The code just takes this key and concatenates it into the url.  So the problem is that for some reason your apikey isn't being processed.  Can you take a look at how you have it encoded to make sure it looks ok?

To the second item - this is an issue but I'm not certain what to do.  You are using a weatherscreen which is the oldest form of weather display.   It hard codes the format of the screen etc. and knows nothing about the units.  These days I exclusively use a timetempscreen for all my weather.  It gives you full formatting ability.  It looks to me like the call to weatherbit is fine - it is retrieving degrees Celsius.  It is just that the fixed format of the weatherscreen sticks that F on it.  I would guess that you were seeing the correct number with the incorrect suffix "F".  I can probably patch something into the weather screen to put the correct appendages on but really I'd suggest you would be better off moving to the timetempscreen for these displays.  

Kevin

**Comment by oddboy** [comment] 2020-10-08 05:56
Hi Kevin,

I got your reply to my second set of questions - about the apikey for weatherbit and the F vs C.  I will try a timetemp screen instead, and I will try again with the api key and see what else I can find out.

with regards to the screen rotation, I must not have described my problem very well.  When my pi boots (with the power line on the bottom side), the screen rotates 90deg clockwise so that the camera module on the SmartPi 2 case is at the top.  Touch works, everything works as far as I can tell.  So it operates in Portrait mode.

Then, I launch soft console, and it displays the softconsole screens as if the screen had never been rotated.  In other words, it's 90deg to left relative to the rest of the desktop, or stated another way, it's sideways in landscape mode.

However, all the touch functions work, and the touches are in the correct places.  I can use softconsole without issue, it's just that it's in landscape mode rather than portrait - but again, touch works while softconsole is running and if i told it in landscape mode, you'd never know the rest of the system is running in Portrait mode.  It's very weird.

the only thing I can think of is that with the 4b, the screen rotation is done with the (software) driver rather than by the hardware?

Anyway, I appreciate your efforts, but unfortunately, it's not the touch that off, it's the whole app - display and touch - relative to the rest of the system.

I may just try disabling the FMKS drivers and configure the "old fashioned" way, but I'm not sure what I'm giving up for that?  DRM I think is one thing...

thanks!

Joel

________________________________

**Comment by kevinkahn** [comment] 2020-10-08 17:38
Joel,
OK - now I (unfortunately) understand.  Some background: the console doesn't use X windows for display management.  It uses the frame buffer (usually at /dev/fb0) and touch events.  So there are 2 separate things to deal with: screen orientation and touch coordinate mapping.  On all previous systems it seems that the screen rotation is handled by firmware/driver/hw so all I do is point the graphics package at /dev/fb0, ask its size, and display to that buffer.  For those systems the rotation done at boot time results in the screen appearing rotated as desired.  On some of those systems the touch coordinates get sorted correctly by the drivers and on some there are issue.  So the touch stuff separately adjusts as needed.  What I thought you were seeing (and what I saw on that display on a Pi3) was that the display rotated with the rest of the system but the touch coordinates were wrong.  Now I get that apparently on the Pi4 the native frame buffer isn't handled at all by the rotation code.

Give this, there isn't an obvious "trivial" fix for the Pi4 approach.  I think I could figure out how to have the console draw to a virtual buffer and then do a transpose at actual frame display time.  That will take me a bit of time to look at.  I'll try to figure out at least the feasibility of that tonight when I get home (I'm in Oregon and will be out most of the day).  It is certainly doable in principle - just a question of how tricky it would be given the program structure and the display library that I use.

Not sure why they did this in the Pi4 the way they did but such is life.  Sorry I can't give you a super quick fix but maybe we can find a way.

Kevin

**Comment by oddboy** [comment] 2020-10-08 19:46
hey Kevin,

OK, that all makes sense now!  Let me see what I can figure out as well through config.  I've been able to get the console rotated using the older methods (lcd_rotate, etc), so maybe I can get both working.

In this case, I'm sure I can work something out, now that I know (difference between X and console is very helpful!).

So don't invest too much for me.  Of course if you think this will be an issue in the future for others, then by all means, and I'm happy to help debug on my system... but if it's just me, then don't worry about it.  I can figure something out.

thanks very much for the time you've put into this!

On the other topics, I m now using a timetemp screen, so no issues there.... One thing I couldn't figure out is how to use the units in a timetemp screen.  I tried inserting some things into the format string in the config.txt (like 'u\00B0'among other things, but just couldn't figure it out.  Not a huge deal, but I was wondering if there's a way that I just haven't come across yet...

cheers, and thanks again for your help, and for this awesome little app!

Joel

________________________________

**Comment by oddboy** [comment] 2020-10-08 22:20
alrighty!

so i disabled the FKMS driver and rotated the display with "display_rotate=1" in the /boot/config.txt file.

then, I switched to beta.

then, I added the /home/pi/Console/touchmodifier file, inserting portraitright

at first, console refused to load saying it couldn't find any touchscreens.  So I looked at the /home/pi/consolebeta/touchdefinitions file and  noticed that the line to rotate the touch points was:

"raspberrypi-ts.portrait|True|0|0|0|800|1.0|1.0|True"

on a whim, I copied that line and edited it so it looks like this:

"raspberrypi-ts.portraitright|True|0|0|0|800|1.0|1.0|True" to match the keyword in the touchmodifier file.

and bingo!  works!

I'm not sure if the same line, but with "raspberrypi-ts.portraitleft" would work the same, or if one of the bits needs to be flipped differently.

but anyway, I now have my Pi4B with 7" Official Touch Screen working in portrait mode!

Thank you!

Joel


________________________________

**Comment by kevinkahn** [comment] 2020-10-09 03:24
Joel,
Glad you got it working that way.  I decided that having soft rotation available might be useful in the long run so I went ahead and figured it out.  Wasn't really too hard to add.  I got rid of that touchmodifer file hack and now do all the setting for soft rotation from the .Screentype file that lives in the home directory (it gets set up in a simple manner at installation).  If has the form a,b,c where b and c are optional.  "a" is what is there now - for your system probably pi7B.  If you want to enable soft rotation add the "b" parameter as 1, 2, 3 where 1 is 90 degree, 2 180, 3 270.  (Actually 4 is 360 which enables the soft rotation code but with a 0 rotation - may be useful for some debugging.)  You shouldn't need the 3rd parameter but it is effectively what was in that touchmodifier file but I now handle it in the expected manner for the given rotation.  I left an option in case I come across a screen that has weird needs.  I pushed this version as a beta - if it isn't too much trouble could you try it out to see that it works as expected on the Pi4?  Since it makes no assumption about the orientation of the underlying system it should but one never knows.  No rush on trying it and if you don't want to do that no problem.

You're going to go "duh!" but the way to display a degree sign is by putting one in the string.  It's a hard character to remember how to generate from the keyboard but open the example file rpi-dev7.txt and there is on on line 234 you can copy.  I never remember how to type it so I always go find one I already have and copy it. :-)

By the way - did you every figure out why the weatherbit apikey wasn't going through?  Want to make sure there isn't some odd bug there.

Kevin
P.S.  The changes were a good exercise since I found a couple of unimportant but real bugs in the code while doing it - always happens.

**Comment by oddboy** [comment] 2020-10-11 10:31
hey Kevin,

I refreshed the beta and removed the touchmodifiers file.  Everything seems to be working a-ok!

when will this go into 'stable'?

thanks for the tip on the degree sign.... you're right .... "D'OH!"

regarding the weather api key, I was doing it wrong..  I didn't configure a provider correctly  I'll go back and gather more detail if it would be helpful to you.

thanks a ton!  super awesome of you to dive right in.

cheers,

Joel

________________________________

**Comment by kevinkahn** [comment] 2020-10-11 17:56
Great.  Do let me know of anything you fine odd, poorly documented, or missing, or just other features you'd like.  I'm always interested is such and since this a hobby I hate to run out of things to play around with.

I have been updating the install stuff to give friendly access to the soft rotation stuff and testing install changes always takes a bit longer because you actually need to do a clean install and try various options.  With luck I will feel ok about pushing a new stable later today or tomorrow.  I'll put a post on the ISY forum and close this issue on github when I do.

Kevin

**Comment by kevinkahn** [comment] 2020-10-11 23:24
Joel,
I just updated the current release version with all the install changes and various other clean ups.  I'll close this issue now but do feel free to ping me on this or other things as needed.  Enjoy!

**Closed as completed by kevinkahn** 2020-10-11 23:24 UTC

**Comment by oddboy** [comment] 2020-10-12 03:05
awesome!  thanks a ton Kevin!

I did have one last question... 😄

I'm trying to get my consoles connected to mqtt, but it looks like the mqtt config section only takes a server address and a password.  However, my broker requires username, password, and client-id.

is there a way to set those?  I tried hacking a bit, but no luck so far.

thanks!

Joel


________________________________
